---
- hosts: all

  tasks:
  - name: find disk space available.
    command: df -hPT

  - name: mc install
    yum: name=mc state=latest

  - name: vim install
    yum: name=vim state=latest

  - name: curl install
    yum: name=mc state=latest

  - name: install update
    yum: name={{item}} state=latest
    with_items:
            - ssh
            - python3-pip
            - net-tools
            - zip
            - git
            - wget


