pipeline 
{

    agent any

    stages 
    {
        stage('Connection test') 
        {
            steps 
            { 
                    sh '''#!/bin/bash
                    echo "bash script is running" 
                    ansible-playbook Ansible-main/playbooks/playbook.yml
                    echo "playbook1 is running" 
                    '''
            }
        }
    }
}
