pipeline 
{

    agent any

    stages 
    {
        stage('Connection test') 
        {
            steps 
            { 
                print  "Hello Vasili"                    
                sh 'ssh root@192.168.9.117 cd home/ubuntu/project && vagrant up'
                print  "vagrant is up!!" 
            }
        }
    }
}
